version: "3.7"
services:

  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: pycharmer/yamdb:latest
    restart: always
    depends_on:
      - db
    ports:
            - "8000:8000"
    volumes:
            - staticfiles:/code/static
    env_file:
      - ./.env

  nginx:
          build: ./nginx
          restart: always
          ports:
                  - "80:80"
                  - "443:443"
          depends_on:
                  - web
          volumes:
                  - staticfiles:/code/static

volumes:
  postgres_data:
  staticfiles:
