version: "3.7"
services:

  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: pycharmer/yamdb:latest
    restart: always
    depends_on:
      - db
    volumes:
            - staticfiles:/code/static
    env_file:
      - ./.env

  nginx:
          image: nginx:1.19.4
          restart: always
          ports:
                  - "80:80"
                  - "443:443"
          depends_on:
                  - web
          volumes:
                  - staticfiles:/code/static
                  - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:
  staticfiles:
