name: yamdb_push_workflow

on: 
  push:
    branches[master]

jobs:
  pep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r derploy/requirements.dev.txt
          
      - name: Lint with flake8
        run: flake8 .

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
            - name: check out the repo
              uses: actions/checkout@v2
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to Docker
              uses: docker/login-action@v1
              with:
                      username: ${{ secrets.DOCKER_USERNAME }}
                      password: ${{ secrets.DOCKER_PSWD }}
            - name: Push to Docker Hub
              uses: docker/build-push-action@v2
              with:
                      push: true
                      tags: pycharmer/yamdb_final:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker-compose up -d

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send notify by telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: The ${{ github.event_name }} event triggered first step.